const TIERS = [
  {
    id: 'essential',
    label: 'Essential',
    subtitle: 'Must-Have Foundation',
    color: 'bronze',
    accent: '#cd7f32',
    description: 'Non-negotiable practices every project must implement',
    categories: [
      {
        name: 'Backend',
        items: [
          { name: 'Input Validation & Sanitization', description: 'Strict allow-list validation on all API inputs; reject invalid data and sanitize dangerous characters', tags: ['validation', 'security', 'api'] },
          { name: 'Authentication & Authorization', description: 'Centralized auth (OAuth2/OpenID), enforce least privilege, never expose secrets', tags: ['auth', 'security', 'api'] },
          { name: 'Error Handling', description: 'Handle errors gracefully; never leak stack traces; return standardized 4xx/5xx responses', tags: ['error-handling', 'api'] },
          { name: 'Performance', description: 'Profile bottlenecks, optimize queries, use caching, meet p95 <200ms SLA', tags: ['performance', 'database', 'caching'] },
          { name: 'Data Modeling & Migrations', description: 'Normalized schemas with referential integrity; versioned and testable migrations', tags: ['database', 'modeling'] },
          { name: 'API Design', description: 'Versioned, documented (OpenAPI), consistent REST/gRPC contracts; no secrets in URLs', tags: ['api', 'documentation'] },
          { name: 'Logging', description: 'Structured centralized logging for ops and security; log auth failures, errors, admin actions', tags: ['logging', 'observability', 'security'] },
          { name: 'Monitoring', description: 'Expose health metrics, set up alerting, track uptime (99.9%), error rates, and latency', tags: ['monitoring', 'observability'] },
          { name: 'Testing', description: 'Automated unit, integration, and API tests; high coverage on core logic', tags: ['testing', 'quality'] },
          { name: 'Security Scanning', description: 'CI-integrated SAST, dependency scanning, vulnerability scans; block critical findings', tags: ['security', 'ci-cd', 'quality'] },
        ],
      },
      {
        name: 'Frontend',
        items: [
          { name: 'Responsive Design', description: 'Fluid layouts, mobile-first approach, flexible grids and media queries', tags: ['responsive', 'ux'] },
          { name: 'Accessibility', description: 'WCAG 2.x compliance; semantic HTML, ARIA roles, contrast 4.5:1, keyboard navigation', tags: ['accessibility', 'ux'] },
          { name: 'Clean Layout & UX', description: 'Consistent design system, intuitive navigation, clear visual hierarchy', tags: ['ux', 'design'] },
          { name: 'Frontend Performance', description: 'Minify and bundle assets, lazy-load, reduce render-blocking scripts; load <2s on 3G', tags: ['performance', 'optimization'] },
          { name: 'Security', description: 'Content Security Policy enabled, sanitize DOM updates, never use innerHTML unsafely', tags: ['security', 'xss'] },
          { name: 'Testing', description: 'Component and unit tests; no broken builds; automated suite runs in CI', tags: ['testing', 'quality'] },
        ],
      },
      {
        name: 'DevOps/Infrastructure',
        items: [
          { name: 'CI/CD Pipeline', description: 'Automated build-test-deploy per commit; failures block merges; track DORA metrics', tags: ['ci-cd', 'automation'] },
          { name: 'Deployment Strategy', description: 'Scripted automated deploys with rollback plan; blue/green or canary deployments', tags: ['deployment', 'reliability'] },
          { name: 'Observability', description: 'Full-stack metrics, logs, and traces; dashboards for error rates, latency, resource usage', tags: ['observability', 'monitoring'] },
          { name: 'Backups and Recovery', description: 'Daily automated backups; test restore procedures; meet RTO requirements', tags: ['backup', 'disaster-recovery'] },
          { name: 'Secrets Management', description: 'All credentials in secure vault; rotate keys regularly; least privilege access', tags: ['security', 'secrets'] },
        ],
      },
      {
        name: 'QA & Testing',
        items: [
          { name: 'Unit Testing', description: 'Isolated tests for core logic; cover branches and edge cases; fast feedback', tags: ['testing', 'quality'] },
          { name: 'Integration Testing', description: 'Test module/service interactions; catch interface mismatches and config issues', tags: ['testing', 'integration'] },
          { name: 'Test Data & Environment', description: 'Realistic anonymized data; prod-like isolated environments; automated provisioning', tags: ['testing', 'environments'] },
          { name: 'Test Automation & CI', description: 'All tests run on every build; no manual gates for release', tags: ['testing', 'ci-cd', 'automation'] },
        ],
      },
      {
        name: 'Security & Compliance',
        items: [
          { name: 'Threat Modeling', description: 'Identify threats early using STRIDE/OWASP; document mitigations as architecture evolves', tags: ['security', 'threat-modeling'] },
          { name: 'OWASP & Secure Coding', description: 'No injection, XSS, CSRF flaws; parameterized queries, CSRF tokens, output encoding', tags: ['security', 'owasp'] },
          { name: 'Encryption', description: 'TLS 1.2+ for transit with strong ciphers; AES-256 for data at rest; secure key management', tags: ['security', 'encryption'] },
          { name: 'Authentication & MFA', description: 'Enforce MFA for admin/sensitive ops; secure JWT/OAuth token handling', tags: ['auth', 'security'] },
          { name: 'Authorization & Least Privilege', description: 'RBAC policies; server-side auth checks at every layer; no excessive permissions', tags: ['auth', 'security'] },
          { name: 'Auditing & Logging', description: 'Immutable audit trails for security events; SIEM monitoring for suspicious patterns', tags: ['security', 'auditing', 'logging'] },
        ],
      },
      {
        name: 'General Codebase',
        items: [
          { name: 'Modularity & Separation', description: 'Single-responsibility modules; loose coupling; each unit independently testable', tags: ['architecture', 'design'] },
          { name: 'Maintainability & Readability', description: 'Clear naming, meaningful comments for complex logic; low cyclomatic complexity', tags: ['quality', 'readability'] },
          { name: 'Style & Conventions', description: 'Automated formatting; consistent indent, naming, and style across the codebase', tags: ['quality', 'style'] },
          { name: 'Documentation', description: 'API docs (Swagger), README with setup; docstrings explain why not what', tags: ['documentation', 'quality'] },
          { name: 'Code Review Process', description: 'Every change peer-reviewed before merge; check design, tests, naming, style', tags: ['process', 'quality'] },
          { name: 'Dependency Management', description: 'Pin versions with lockfiles; automate vulnerability patching; no untrusted sources', tags: ['dependencies', 'security'] },
          { name: 'Commit Discipline', description: 'Clear commit messages with context; atomic commits for single logical changes', tags: ['process', 'git'] },
        ],
      },
    ],
  },
  {
    id: 'recommended',
    label: 'Recommended',
    subtitle: 'Growth & Quality',
    color: 'silver',
    accent: '#c0c0c0',
    description: 'Practices that elevate quality, maintainability, and team velocity',
    categories: [
      {
        name: 'Backend',
        items: [
          { name: 'Centralized Validation', description: 'Use schema validators and library-based validation for consistency across endpoints', tags: ['validation', 'api'] },
          { name: 'RBAC/ABAC & SSO', description: 'Implement role/attribute-based access control with Single Sign-On integration', tags: ['auth', 'security'] },
          { name: 'Graceful Degradation', description: 'User-friendly error messages with fallback behavior when services are unavailable', tags: ['error-handling', 'ux'] },
          { name: 'CDN & Rate Limiting', description: 'Use CDNs for static content; implement rate limiting to protect API resources', tags: ['performance', 'security'] },
          { name: 'Denormalized Read Models', description: 'Optimize read paths with denormalized views; document ER models comprehensively', tags: ['database', 'performance'] },
          { name: 'Pagination & HATEOAS', description: 'Consistent pagination; hypermedia links for discoverable API navigation', tags: ['api', 'design'] },
          { name: 'Structured Logging', description: 'JSON/CEF formatted logs with correlation IDs for distributed tracing', tags: ['logging', 'observability'] },
          { name: 'Distributed Tracing', description: 'Trace requests across services (Jaeger/Zipkin); detect latency anomalies', tags: ['monitoring', 'observability'] },
          { name: 'E2E User Flow Tests', description: 'End-to-end tests covering critical user journeys; track test coverage metrics', tags: ['testing', 'quality'] },
          { name: 'Iterative Threat Modeling', description: 'Update threat models as design changes; regular penetration testing schedule', tags: ['security', 'threat-modeling'] },
        ],
      },
      {
        name: 'Frontend',
        items: [
          { name: 'Framework Grids/Flex', description: 'Use CSS frameworks (Bootstrap/Tailwind) for consistent responsive layouts', tags: ['responsive', 'css'] },
          { name: 'Accessibility Audits', description: 'Automated checks with Lighthouse/axe; manual screen reader testing', tags: ['accessibility', 'testing'] },
          { name: 'Component Library', description: 'Adopt or build a design system / UI component library for visual consistency', tags: ['design', 'reusability'] },
          { name: 'Component Reusability', description: 'Build DRY components; document with Storybook for team consumption', tags: ['reusability', 'architecture'] },
          { name: 'Central State Management', description: 'Redux/Vuex/Context for predictable unidirectional data flow', tags: ['state-management', 'architecture'] },
          { name: 'CDN & PWA Optimization', description: 'Serve static assets via CDN; Service Worker for offline support', tags: ['performance', 'pwa'] },
          { name: 'Security Headers', description: 'X-Frame-Options, X-Content-Type-Options, Referrer-Policy headers', tags: ['security', 'headers'] },
          { name: 'E2E Critical Flows', description: 'Automated browser tests (Cypress/Playwright) for login, checkout, core workflows', tags: ['testing', 'e2e'] },
        ],
      },
      {
        name: 'DevOps/Infrastructure',
        items: [
          { name: 'Staging Environment', description: 'Deploy to staging before production; automated rollback on failure', tags: ['ci-cd', 'deployment'] },
          { name: 'Multi-Region & Feature Flags', description: 'Multi-region deployment with feature flags for gradual rollout', tags: ['deployment', 'scalability'] },
          { name: 'Centralized Monitoring Stack', description: 'ELK/EFK for logs; Prometheus/Grafana for metrics; unified dashboards', tags: ['monitoring', 'observability'] },
          { name: 'Resilience Patterns', description: 'Circuit breakers, retries with backoff, bulkheads to isolate failures', tags: ['resilience', 'architecture'] },
          { name: 'Automated Snapshots', description: 'Automated DB snapshots with cold storage archival for long-term retention', tags: ['backup', 'disaster-recovery'] },
          { name: 'GitOps Workflows', description: 'ArgoCD/Flux for declarative Git-driven infrastructure management', tags: ['gitops', 'automation'] },
          { name: 'Automated Secret Injection', description: 'Short-lived credentials injected at runtime from vault; rotate automatically', tags: ['secrets', 'security'] },
          { name: 'Synthetic Monitoring', description: 'Heartbeat/uptime checks; synthetic transactions for critical user paths', tags: ['monitoring', 'testing'] },
        ],
      },
      {
        name: 'QA & Testing',
        items: [
          { name: 'TDD & Coverage Thresholds', description: 'Test-driven development; enforce minimum coverage thresholds in CI', tags: ['testing', 'quality'] },
          { name: 'Service Mocks & Test Envs', description: 'Use mocks/stubs for external services; dedicated test environments', tags: ['testing', 'integration'] },
          { name: 'Browser-Based E2E', description: 'Cypress/Playwright/Selenium for automated browser testing', tags: ['testing', 'e2e'] },
          { name: 'Performance Benchmarks', description: 'Set and track performance benchmarks; continuous load testing', tags: ['testing', 'performance'] },
          { name: 'Synthetic Test Data', description: 'Data versioning; Faker/synthetic generators for realistic test data', tags: ['testing', 'data'] },
          { name: 'Coverage Badges in PR', description: 'Test reports and coverage badges visible in pull requests', tags: ['testing', 'ci-cd'] },
        ],
      },
      {
        name: 'Security & Compliance',
        items: [
          { name: 'Design-Time Threat Updates', description: 'Update threat model as architecture evolves; review during design phase', tags: ['security', 'threat-modeling'] },
          { name: 'Security Code Reviews', description: 'Regular peer reviews focused on security; checklist-based review process', tags: ['security', 'code-review'] },
          { name: 'HSTS & Cert Pinning', description: 'HTTP Strict Transport Security; certificate pinning for mobile/web clients', tags: ['security', 'encryption'] },
          { name: 'OAuth2/SAML SSO', description: 'Single Sign-On with session timeouts; secure token refresh flows', tags: ['auth', 'security'] },
          { name: 'ABAC & Attribute Controls', description: 'Attribute-based access control for fine-grained authorization decisions', tags: ['auth', 'security'] },
          { name: 'SIEM Anomaly Alerts', description: 'SIEM-based log monitoring; alert on brute-force and anomalous access patterns', tags: ['security', 'monitoring'] },
          { name: 'Privacy Impact Assessment', description: 'Assess data collection/processing; document breach response plan', tags: ['compliance', 'privacy'] },
          { name: 'Pre-Launch Pen Testing', description: 'Full penetration test before major releases; address critical findings', tags: ['security', 'testing'] },
          { name: 'Dependency Patching', description: 'Promptly patch known vulnerabilities; maintain minimal dependency footprint', tags: ['dependencies', 'security'] },
        ],
      },
      {
        name: 'General Codebase',
        items: [
          { name: 'Layered Architecture', description: 'Clear separation into layers (presentation, business, data); defined service boundaries', tags: ['architecture', 'design'] },
          { name: 'Microservices & Queues', description: 'Decouple services with message queues; API-first microservice design', tags: ['architecture', 'scalability'] },
          { name: 'Tech Debt Tracking', description: 'Regular refactoring sprints; track and prioritize technical debt items', tags: ['quality', 'maintainability'] },
          { name: 'Automated Formatting', description: 'Pre-commit hooks with Prettier/dprint; consistent formatting enforced', tags: ['style', 'quality'] },
          { name: 'Architecture Diagrams', description: 'Keep ADRs and C4 diagrams versioned alongside the code', tags: ['documentation', 'architecture'] },
          { name: 'Review Checklist', description: 'Structured reviewer checklist; rotate reviewers across the team', tags: ['process', 'quality'] },
          { name: 'Trunk-Based or GitFlow', description: 'Short-lived branches; main always green; tagged releases', tags: ['git', 'process'] },
          { name: 'Minimal Deps Policy', description: 'SCA scanning; approve new dependencies; prefer stdlib', tags: ['dependencies', 'quality'] },
        ],
      },
    ],
  },
  {
    id: 'advanced',
    label: 'Advanced',
    subtitle: 'Production Excellence',
    color: 'gold',
    accent: '#ffd700',
    description: 'Production-hardening practices for scale, resilience, and maturity',
    categories: [
      {
        name: 'Backend',
        items: [
          { name: 'Formal & Property Tests', description: 'Auto-generated property-based testing; formal verification for critical paths', tags: ['testing', 'quality'] },
          { name: 'Zero Trust Architecture', description: 'MFA for all high-value actions; verify every request regardless of origin', tags: ['security', 'auth'] },
          { name: 'Circuit Breakers', description: 'Chaos-test error flows; circuit breaker patterns to prevent cascade failures', tags: ['resilience', 'error-handling'] },
          { name: 'Advanced Caching Layers', description: 'Multi-level caching (CDN + redis + in-memory); peak load scalability testing', tags: ['performance', 'caching'] },
          { name: 'Migration Audit & Dry-Run', description: 'Automated migration audits; dry-run migrations before applying to production', tags: ['database', 'reliability'] },
          { name: 'API Gateway & GraphQL/gRPC', description: 'Gateway for auth/routing/rate-limiting; schema registry for inter-service contracts', tags: ['api', 'architecture'] },
          { name: 'Immutable Append-Only Logs', description: 'WORM-compliant log storage; log sampling for scale; tamper-evident audit trails', tags: ['logging', 'security'] },
          { name: 'AI-Based Anomaly Detection', description: 'Per-user/per-transaction analytics; ML-driven anomaly detection in metrics/logs', tags: ['monitoring', 'ai'] },
          { name: 'Fuzz & Model-Based Tests', description: 'Fuzz testing public interfaces; model-based testing for complex state machines', tags: ['testing', 'security'] },
          { name: 'Bug Bounty & Third-Party Audit', description: 'Public bug bounty program; third-party security audit before major launches', tags: ['security', 'testing'] },
        ],
      },
      {
        name: 'Frontend',
        items: [
          { name: 'Multi-Device Testing', description: 'Test on real devices; AMP for content pages; responsive testing matrix', tags: ['responsive', 'testing'] },
          { name: 'WCAG AA/AAA Compliance', description: 'Full accessibility audit; user testing with assistive technology', tags: ['accessibility', 'testing'] },
          { name: 'Dark Mode & Theming', description: 'Full dark mode support; design critique/review cycle for UI changes', tags: ['design', 'ux'] },
          { name: 'i18n-Ready Components', description: 'Internationalization-ready with theming; locale-aware formatting', tags: ['i18n', 'architecture'] },
          { name: 'Immutable State & Offline Sync', description: 'Immer/immutable state patterns; offline queue with background sync', tags: ['state-management', 'offline'] },
          { name: 'SSR/Pre-Rendering', description: 'Server-side rendering or static pre-rendering for initial load speed', tags: ['performance', 'seo'] },
          { name: 'CSP & App Containerization', description: 'Strict CSP enforcement; front-end in isolated app container', tags: ['security', 'architecture'] },
          { name: 'Visual Regression Testing', description: 'Screenshot-based visual diff; beta user trials before release', tags: ['testing', 'quality'] },
        ],
      },
      {
        name: 'DevOps/Infrastructure',
        items: [
          { name: 'Chaos Engineering Drills', description: 'Regular chaos experiments; test resilience to infrastructure failures', tags: ['resilience', 'testing'] },
          { name: 'Zero-Downtime Upgrades', description: 'Rolling updates with health checks; canary analysis for safe rollouts', tags: ['deployment', 'reliability'] },
          { name: 'AI/ML Anomaly on Logs', description: 'ML-based anomaly detection on log patterns and metric trends', tags: ['observability', 'ai'] },
          { name: 'Cross-Region Failover', description: 'Service mesh (Istio/Linkerd) for traffic management; automatic region failover', tags: ['scalability', 'resilience'] },
          { name: 'Geo-Redundant Snapshots', description: 'Cross-region backup replication; RPO/RTO validation drills', tags: ['backup', 'disaster-recovery'] },
          { name: 'Immutable Infrastructure', description: 'No manual changes; all infra replaced not modified; golden AMI/container images', tags: ['infrastructure', 'automation'] },
          { name: 'HSM & Granular Audit', description: 'Hardware security modules; cryptographically verifiable audit trails', tags: ['security', 'compliance'] },
          { name: 'Business-Level SLI/SLO', description: 'Business-transaction SLIs; error budgets drive release decisions', tags: ['monitoring', 'reliability'] },
        ],
      },
      {
        name: 'QA & Testing',
        items: [
          { name: 'Mutation Testing', description: 'Assess test quality by introducing code mutations; ensure tests catch them', tags: ['testing', 'quality'] },
          { name: 'Contract Testing (Pact)', description: 'Consumer-driven contract tests for microservice API compatibility', tags: ['testing', 'microservices'] },
          { name: 'Real Browser & Device CI', description: 'Run E2E tests on real browser engine and mobile devices in CI', tags: ['testing', 'e2e'] },
          { name: 'AFL/OSS-Fuzz Integration', description: 'Continuous fuzzing integrated into security testing pipeline', tags: ['testing', 'security'] },
          { name: 'Chaos & Stress Testing', description: 'Chaos experiments beyond expected load; test system limits', tags: ['testing', 'resilience'] },
          { name: 'Live-Cloned Staging Data', description: 'Production data clones with masking; staging mirrors production exactly', tags: ['testing', 'environments'] },
          { name: 'Self-Healing & Pipeline Reviews', description: 'Auto-retry flaky tests; treat pipeline config with same rigor as app code', tags: ['testing', 'ci-cd'] },
        ],
      },
      {
        name: 'Security & Compliance',
        items: [
          { name: 'Red-Team Simulations', description: 'Full red-team attack scenarios; test detection and response capabilities', tags: ['security', 'testing'] },
          { name: 'DAST in Pipeline', description: 'Dynamic application security testing as part of CI/CD pipeline', tags: ['security', 'ci-cd'] },
          { name: 'FIPS & Perfect Forward Secrecy', description: 'FIPS-validated crypto modules; PFS cipher suites for all TLS', tags: ['security', 'encryption'] },
          { name: 'Biometric & Risk-Based Auth', description: 'Biometric 2FA on all accounts; risk-based stepped-up authentication', tags: ['auth', 'security'] },
          { name: 'JIT & Continuous Access Review', description: 'Just-In-Time privilege elevation; continuous access certification', tags: ['auth', 'security'] },
          { name: 'WORM & Blockchain Audit', description: 'Write-Once-Read-Many audit storage; blockchain-based tamper-proof logs', tags: ['security', 'auditing'] },
          { name: 'SOC 2 / ISO 27001', description: 'Formal certification process; third-party attestation for compliance frameworks', tags: ['compliance', 'audit'] },
          { name: 'Supply-Chain Signing', description: 'Signed dependencies; vetted package policy; SLSA compliance', tags: ['dependencies', 'security'] },
        ],
      },
      {
        name: 'General Codebase',
        items: [
          { name: 'DDD & Hexagonal Architecture', description: 'Domain-driven design with hexagonal/ports-and-adapters architecture', tags: ['architecture', 'design'] },
          { name: 'Event-Driven & CQRS', description: 'Event-driven microservices with CQRS/event sourcing for complex domains', tags: ['architecture', 'scalability'] },
          { name: 'Continuous Quality Metrics', description: 'Track code quality trends; dedicated refactoring sprints each cycle', tags: ['quality', 'process'] },
          { name: 'Strict Lint Rules', description: 'Language-specific idiomatic rules; no warnings allowed in CI', tags: ['style', 'quality'] },
          { name: 'ADR Versioned with Code', description: 'Architecture Decision Records stored alongside code; lightweight RFC process', tags: ['documentation', 'architecture'] },
          { name: 'Mob Review & Pair Programming', description: 'Regular pair/mob programming sessions; cross-team code audits', tags: ['process', 'quality'] },
          { name: 'Auto-Changelog from Commits', description: 'Conventional commits auto-generate changelog and version bumps', tags: ['git', 'automation'] },
          { name: 'Private Artifact Registry', description: 'Internal package registry; vetted and signed internal dependencies', tags: ['dependencies', 'security'] },
          { name: 'Quality Gates at 90%', description: 'Sonar quality gates enforce coverage, duplication, and complexity thresholds', tags: ['quality', 'automation'] },
        ],
      },
    ],
  },
  {
    id: 'finalize',
    label: 'Finalize Kit',
    subtitle: 'Pre-Release Gate',
    color: 'platinum',
    accent: '#a78bfa',
    description: 'Final checks before every release — the launch readiness gate',
    categories: [
      {
        name: 'Code Quality & Testing',
        items: [
          { name: 'All Code Reviewed & Merged', description: 'Every change reviewed and merged to main; CI pipeline passes with all checks green', tags: ['process', 'quality'] },
          { name: 'All Test Suites Passing', description: 'Unit, integration, and E2E tests pass in CI; no high-severity bugs open', tags: ['testing', 'quality'] },
          { name: 'Static Analysis & Linters Clean', description: 'SAST and linter checks show no errors; code coverage targets met for critical paths', tags: ['quality', 'automation'] },
          { name: 'Fuzz & Load Tests Clear', description: 'No critical failures in fuzz testing; load tests demonstrate required throughput', tags: ['testing', 'performance'] },
          { name: 'Mutation Tests Pass (if used)', description: 'Test suite catches injected mutations; test quality is validated', tags: ['testing', 'quality'] },
        ],
      },
      {
        name: 'Security & Compliance',
        items: [
          { name: 'Dependency Scans Clean', description: 'No critical vulnerabilities in dependencies; SCA scan passes', tags: ['dependencies', 'security'] },
          { name: 'SAST/DAST Scans Pass', description: 'Static and dynamic security scans show no critical findings', tags: ['security', 'testing'] },
          { name: 'OWASP Top 10 Addressed', description: 'All OWASP Top 10 categories reviewed and mitigated', tags: ['security', 'owasp'] },
          { name: 'Pen Test Findings Resolved', description: 'No unresolved high-risk findings from penetration testing', tags: ['security', 'testing'] },
          { name: 'Threat Model Updated', description: 'Threat model reflects current architecture with mitigations documented', tags: ['security', 'threat-modeling'] },
          { name: 'Legal & Privacy Complete', description: 'Licensing, export control, and privacy (GDPR/HIPAA) reviews finalized', tags: ['compliance', 'privacy'] },
        ],
      },
      {
        name: 'Operations & Infrastructure',
        items: [
          { name: 'Deployment Scripts Tested', description: 'Deployment scripts validated in staging; rollback procedure verified', tags: ['deployment', 'reliability'] },
          { name: 'Backup & Restore Verified', description: 'Automated backup verified; restore procedure tested successfully', tags: ['backup', 'disaster-recovery'] },
          { name: 'Instrumentation in Place', description: 'Metrics, logs, and tracing configured for production monitoring', tags: ['monitoring', 'observability'] },
          { name: 'Dashboards & Alerts Ready', description: 'Dashboards for key SLIs; alerts configured for SLA breaches', tags: ['monitoring', 'reliability'] },
          { name: 'SLAs/SLOs Defined', description: 'e.g. 99.9% uptime, p95 <200ms, error rate <0.1%; alert thresholds set', tags: ['reliability', 'monitoring'] },
          { name: 'Rollback Plan Verified', description: 'Automated rollback tested; can revert within defined RTO', tags: ['deployment', 'reliability'] },
          { name: 'Secrets Stored Securely', description: 'All secrets in vault/secret store; no hardcoded credentials', tags: ['secrets', 'security'] },
          { name: 'Configs Per Environment', description: 'Timeouts, endpoints, and feature flags in env-specific config', tags: ['configuration', 'reliability'] },
        ],
      },
      {
        name: 'Documentation & Release',
        items: [
          { name: 'API Documentation Updated', description: 'OpenAPI/Swagger docs reflect latest endpoints and schemas', tags: ['documentation', 'api'] },
          { name: 'Release Notes Drafted', description: 'Changelog/release notes written with upgrade instructions and breaking changes', tags: ['release', 'documentation'] },
          { name: 'Version Number Incremented', description: 'Semantic version bumped according to change scope', tags: ['release', 'process'] },
          { name: 'Smoke Test Passed', description: 'Final sanity check in production-like environment passes all critical flows', tags: ['testing', 'release'] },
          { name: 'Stakeholder Sign-Off', description: 'Security, ops, and product stakeholders have signed off on the release', tags: ['process', 'release'] },
          { name: 'DORA Metrics Healthy', description: 'Lead time <1 week; deployment frequency weekly; change failure rate low', tags: ['metrics', 'reliability'] },
        ],
      },
    ],
  },
];

module.exports = { TIERS };
